## 1. Numpy

    * 파이썬에서 수학적인 계산(행렬, 벡터, 차원)을 편하게 할 수 있도록 돕는 라이브러리
    

In [1]:
%pip install numpy

In [2]:
import numpy as np

In [7]:
# 1차원 배열
arr1 = np.array([1,2,3])

arr1
type(arr1)
arr1.shape  # 1행 3열
arr1.ndim   # 1차원

1

In [14]:
# 2차원 배열
arr2 = np.array([[1,2,3], [1,2,3]])

arr2
type(arr2)
arr2.shape  # 2행 3열
arr2.ndim   # 2차원

2

In [20]:
# ndarray 데이터 타입

arr3 = ['1','2','3']

arr3 = np.array(arr3)
arr3 = arr3.astype(np.int64)
arr3.dtype

dtype('int64')

In [28]:
# ndarray 생성
arr = np.arange(10)

arr > 5 # boolean indexing

arr[[False, False, False, False, False, False,  True,  True,  True, True]]  # arr[arr > 5]


array([6, 7, 8, 9])

In [32]:
np.zeros((3,2))
np.ones((3,2))
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
# reshape > 차원 변경

arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
# indexing & slicing
arr[0]
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
# numpy 몇 가지
# 01. 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요.
# np.mean()

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape

print(arr)
# axis=0(열), axis=1(행), axis=2(채널)
np.mean(arr, axis=1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [47]:
# 02. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요
arr = np.array([1,2,3,4,5,6])

even_indexs = np.arange(0, arr.size, 2)
print(arr[even_indexs])

[1 3 5]


In [49]:
# 03. 2차원 배열의 주 대각성 상에 있는 원소들을 출력하는 코드를 작성하세요.
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr.shape

# diag
np.diag(arr)

array([1, 5, 9])

In [53]:
# 04. 2차원 배열에서 각 열의 표준 편차를 계산하는 코드를 작성하세요.
# 표준 편차 > np.std()

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.std(arr)
print(arr)

np.std(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

In [55]:
# 05. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.

arr = np.array([1,2,3,4,5])

np.median(arr)

3.0

In [59]:
# 06. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.
# - boolean indexing

arr = np.array([1,4,6,3,9,2,7,8])
arr[arr >= 5]

array([6, 9, 7, 8])

In [60]:
# 07. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.

arr = np.array([1,3,5,2,4,6,3,5,7])

np.where((arr == 3) | (arr == 5))

(array([1, 2, 6, 7]),)